pipeline {
    agent any
    parameters {
        string(name: 'SOURCE_ENVIRONMENT', description: 'Source Environment', defaultValue: 'dev')
        string(name: 'REPORT_NAME', description: 'Report Name', defaultValue: 'sample')
        string(name: 'WORKSPACE_NAME', description: 'Workspace Name', defaultValue: 'Source')
    }
    environment {
        TENANTID = credentials("pbi-${params.SOURCE_ENVIRONMENT}-tenantid")
        PBI_CREDS = credentials("pbi-${params.SOURCE_ENVIRONMENT}")
    }
    stages {
        stage('Export') {
            steps {
                sh "chmod +x -R $WORKSPACE"
                sh '$WORKSPACE/export/export-report.sh $WORKSPACE_NAME $REPORT_NAME'
                archiveArtifacts artifacts: "${REPORT_NAME}.pbix"
                // echo "Git URL is ${GIT_URL}"
                // sh "echo 'Git URL is ${GIT_URL}'"
                // withCredentials([
                //     usernamePassword(
                //         credentialsId: 'git-pass-credentials-ID',
                //         passwordVariable: 'GIT_PASSWORD',
                //         usernameVariable: 'GIT_USERNAME'
                //     )
                // ]) {
                //     String exportBranchName = "pbi-export/${BUILD_TAG}-$SourceWorkspaceName-$SourceReportName"
                //     // git checkout -b $exportBranchName
                //     // git commit -am "[$BUILD_TAG] $SourceWorkspaceName/$SourceReportName"
                //     sh("git push -u origin $exportBranchName")
                // }
            }
        }
    }
}
