#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

  version: '3.7'
  services:
    jenkins:
      image: jenkins/jenkins:lts-jdk11

      user: root

      ports:
        - 8080:8080 
        - 50000:50000

  #     # Uncomment to access Azure VPN and rebuild container
  #     # network_mode: bridge

  #     labels:
  #       - "com.jenkins.powerbi=Jenkins Power BI"

      volumes:
        - ..:/tf/caf
        - ~/.ssh:/tmp/.ssh-localhost:ro
        - /var/run/docker.sock:/var/run/docker.sock

  #     # Overrides default command so things don't shut down after the process ends.
  #     command: /bin/sh -c "while sleep 1000; do :; done"

  # volumes:
  #   volume-caf-vscode:
  #     labels:
  #       - "caf=Azure CAF"
  #   volume-caf-vscode-bashhistory:
